version: '3'
services:
  frontend:
    container_name: vue
    image: nginx:1.21
    depends_on:
      - backend
    restart: unless-stopped  
    networks:
      - axisbits_apploc

  backend:
    container_name: php    
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - database
    restart: unless-stopped  
    networks:
      - axisbits_apploc

  database:
    container_name: mysql
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
        - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - axisbits_apploc

  nginx:
    container_name: nginx
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html      
    depends_on:
      - frontend
      - backend
    restart: unless-stopped  
    networks:
      - axisbits_apploc

networks:
  axisbits_apploc:

volumes:
    mysql-data:    
